name: Linux Build
on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for Updates
        run: sudo apt-get update -y

      - name: Install Required Packages
        run: sudo apt-get install -y git make cmake clang libbz2-dev build-essential default-libmysqlclient-dev

      - name: Update Compilers
        run: source ci-compiler-update.sh

      - name: Build Mangos Project
        run: source ci-compile.sh
